Updated ReadWrite Lock to enforce best practice
mixpanel/mixpanel-swift pull request #576
Opened 2023-01-04 11:12 UTC by vikas171999

- Corrected Spelling mistake
- Removed unneeded self
- made concurrentQueue private as it is not used outside that class. And as apple suggests if we are not using anything outside the class we should always make it private. We should upgrade the access level as and when the variable needed outside

2023-01-09 21:55 UTC, jaredmixpanel requested changes
small typo and please also pull in the latest changes from master, to get updated CI config.

2023-01-09 21:55 UTC, jaredmixpanel commented on Sources/ReadWriteLock.swift
> +        concurrenttQueue.sync {
```suggestion
        concurrentQueue.sync {
```

2023-01-22 17:06 UTC, vikas171999 commented on Sources/ReadWriteLock.swift
> +        concurrenttQueue.sync {
Done

2023-01-24 21:42 UTC, jaredmixpanel commented
@vikas171999 CI is still failing. Please merge the latest upstream master to get the updates to our CI config.

2023-02-27 21:04 UTC, jaredmixpanel commented
@vikas171999 can you please pull in the latest changes from master? they include some CI config changes that will fix your CI failure.

2023-03-01 00:27 UTC, closed without merging